- package-lock.json
- package.json
- Install mongodb
- Create account and connect database
> [Task] Connect db and install mongodb

- .prettierrc
- package-lock.json
- package.json
- Config prettier
- Install prettier tailwind css
> [Task] Config prettier

- prisma/schema.prisma
- Design User Table
- Write Prisma schema
> [Task] Design and write schema for user table

- prisma/schema.prisma
- Design table event
- Create prisma schema
> [Task]Design and create prisma shcema for event table

- app/routes/_index.tsx
- app/routes/login.tsx
- app/server/auth.server.ts
- app/server/prisma.server.ts
- app/server/user.server.ts
- app/utils/types.server.ts
- app/utils/validators.server.ts
- package-lock.json
- package.json
- Create login & register API
- Create auth route
- Set cookie's expired date
> [Task] Create login & register API

- app/server/formAction.server.ts
- app/shared/components/form.tsx
- package-lock.json
- package.json
- Custom form component using remix-form
> [Task] Create custom form using remix-form

- .github/pull_request_template.md
- package-lock.json
- stylesheet/base/_mixins.scss
- stylesheet/base/_variables.scss
- stylesheet/layout/_grid.scss
> Config grid layout
> add file pull request template
> Config grid layout 

- app/server/event.server.ts
- app/shared/utils/types.server.ts
> Create api new event

- app/server/event.server.ts
- app/shared/components/FormEvent.tsx
- assets/icons/ic-trash.svg
- stylesheet/modules/_icon.scss
- stylesheet/pages/_home.scss
> [Story-4] Create UI delete event

- app/shared/components/FormEvent.tsx
> Disable days in the past of date input
> [Task] Disable days in the past of date input

- app/routes/event.$eventId_.edit.tsx
- app/routes/event.create.tsx
> Navigate when edit create event success
> [Task] Navigate when edit create event success

- app/routes/events.tsx
- assets/icons/ic-plus.svg
- stylesheet/modules/_icon.scss
> [Task] Create add and back button

- app/routes/events.$eventId_.delete.tsx
- app/routes/events.$eventId_.edit.tsx
- app/routes/events.create.tsx
- app/routes/events.tsx
- app/server/event.server.ts
- app/shared/components/FormEvent.tsx
- app/shared/constant/validator.ts
- Modify navigation when trigger event
- Modify delete funciton
> [Task] Modify navigation and delete function

- app/routes/events.tsx
- app/shared/components/Sidebar.tsx
> [Task] Separate sidebar component

- app/routes/events.$eventId_.edit.tsx
- app/shared/components/CalendarWrapper.tsx
- stylesheet/modules/_calendar.scss
- Customize calendar cell
- Handle event on click
- Limit displayed event number
> [Task] Customize calendar cell

- app/routes/events.tsx
- app/server/event.server.ts
- app/shared/components/CalendarWrapper.tsx
- app/shared/utils/convertDateString.ts
- Create get all events in day API
- Implement API
- Customize prev, next, day filter button
> [Task] Create get all events in a day api, handle move forward and backward

- app/routes/events.$eventId.tsx
- app/routes/events.$eventId_.edit.tsx
- app/routes/events.tsx
- app/shared/components/FormEvent.tsx
- app/shared/components/Modal.tsx
- app/shared/components/modals_form/ConfirmDeleteEvent.tsx
- app/shared/helper/resolveModal.server.ts
- app/shared/utils/getSearchParams.server.ts
- stylesheet/base/_reset.scss
- stylesheet/modules/_all.scss
- stylesheet/modules/_modal.scss
- Create modal UI and functionality
- Modify delete event using confirm modal
> [Task] Create modal and modify delete event using confirm modal

- app/routes/events.$eventId_.delete.tsx
- app/routes/events.restore.tsx
- app/server/event.server.ts
- app/shared/components/CalendarWrapper.tsx
- app/shared/middleware/softDeleteEvent.ts
- app/shared/utils/formatNumberToDateString.ts
- prisma/schema.prisma
- Redesign database
- Create soft delete event API
- Modify loader get events by day and get events by month
> [Enhance] Create soft delete event and redesign database

- app/shared/components/CalendarWrapper.tsx
- app/shared/components/Sidebar.tsx
- app/shared/components/modals_form/ConfirmDeleteEvent.tsx
- Fix extra week display in month view
- Clear logger
> [Fix-bug] Fix extra week display in month view

- app/routes/events.tsx
- app/shared/components/modals_form/ShowEventDetail.tsx
- Modify event data of loader
- Check current user id
> [Fix-bug] Show edit and delete button if this event is current user event

- app/shared/components/CalendarWrapper.tsx
> Add filter by week
> Sync query param and ui when filter
> [Task] Sync query param and ui when filter

- app/routes/login.tsx
- stylesheet/pages/_login.scss
> Responsive all page on tablet
> [Task] Responsive all page on tablet

- app/shared/components/EventList.tsx
- app/shared/components/Sidebar.tsx
- Modify spinner loading condition
> [Fix-bug] Fix loading when user take action

- app/routes/events.tsx
- app/server/event.server.ts
- app/shared/components/Sidebar.tsx
- Modify show today event list
> [Task] Show today event list to sidebar

- app/routes/events.create.tsx
- app/server/event.server.ts
- app/shared/utils/mailSender.ts
- app/shared/utils/types.server.ts
- app/styles/app.css
- package-lock.json
- package.json
- Send email to guest when create event
> [Task] Send email to guest when create event
